"""added some things

Revision ID: c4da844fe0aa
Revises: 
Create Date: 2024-07-21 11:56:04.955655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4da844fe0aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('message', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'message', 'user', ['user_id'], ['id'])
    op.drop_column('message', 'sender_name')
    op.drop_column('message', 'date')
    op.add_column('review', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('review', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'review', 'user', ['user_id'], ['id'])
    op.drop_column('review', 'date')
    op.add_column('user', sa.Column('role', sa.String(length=50), nullable=False))
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('user', 'first_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_column('user', 'role')
    op.add_column('review', sa.Column('date', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'timestamp')
    op.drop_column('review', 'user_id')
    op.add_column('message', sa.Column('date', sa.DATETIME(), nullable=True))
    op.add_column('message', sa.Column('sender_name', sa.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'timestamp')
    op.drop_column('message', 'user_id')
    # ### end Alembic commands ###
